"""seed data

Revision ID: 8dbd92e6bb23
Revises: 0c66dcb39eaf
Create Date: 2025-02-23 12:02:04.091216

"""

from collections.abc import Sequence
from typing import cast

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Table

from database.models import User

# revision identifiers, used by Alembic.
revision: str = "8dbd92e6bb23"
down_revision: str | None = "0c66dcb39eaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

users = [{"id": 1, "username": "husan", "email": "husan.eshonqulov.00@gmail.com"}]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = cast(Table, User.__table__)
    op.bulk_insert(table=users_table, rows=users)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = cast(Table, User.__table__)
    op.execute(users_table.delete().where(users_table.c.id == 1))
    # ### end Alembic commands ###
